[general]
import = ["~/.config/alacritty/themes/wallhaven-e7r958.toml"]

[window]
dimensions = { columns = 95, lines = 21 }
padding = { x = 20, y = 20 }
startup_mode = "Windowed"
decorations = "Full"

[font]
size = 10.0

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
