# Borders / gaps
default_border pixel 0
default_floating_border pixel 1
hide_edge_borders smart

gaps inner 5
gaps outer 3
smart_gaps on

# Per-workspace gap override
workspace 5 gaps horizontal 100
workspace 5 gaps vertical 50
workspace 5 gaps inner 10

# Window colors: border / background / text / indicator / child_border
client.focused          #c99a5b #c99a5b #1c140a #e3b284 #c99a5b
client.focused_inactive #4a3c2a #4a3c2a #e4d3b0 #4a3c2a #4a3c2a
client.unfocused        #16110b #16110b #6b5a42 #16110b #16110b
client.urgent           #b3542e #b3542e #1c140a #b3542e #b3542e

bar {
    status_command i3blocks -c ~/.config/i3blocks/config
    position top
    separator_symbol "::"
    font pango: JetBrains Mono Nerd Font 9
    tray_output primary
    tray_padding 4

    colors {
        background #16110b
        statusline #e4d3b0
        separator  #4a3c2a

        focused_workspace  #c99a5b #c99a5b #1c140a
        active_workspace   #4a3c2a #4a3c2a #e4d3b0
        inactive_workspace #16110b #16110b #6b5a42
        urgent_workspace   #b3542e #b3542e #1c140a
    }
}
