backend = "glx";
vsync = true;

# Opacity
inactive-opacity = 1;
active-opacity = 1;
frame-opacity = 1;

opacity-rule = [
    "90:class_g = 'Alacritty' && focused",
    "85:class_g = 'Alacritty' && !focused",
    "100:window_type = 'dock'",
    "100:class_g = 'dmenu'",
    "100:fullscreen"
];

# Blur (leve)
blur-method = "dual_kawase";
blur-strength = 2;
blur-background = true;
blur-background-fixed = true;
blur-background-exclude = [
    "window_type = 'dock'",
    "window_type = 'desktop'"
];
